name: lite_embeddings_dart_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  json_annotation: ^4.9.0
  lite_embeddings_dart:
    path: '/Users/jan/Project/lite_embeddings_dart'

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.0
  dio: ^5.5.0+1
  dotenv: ^4.2.0
